name: Update directories.json

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backup del file JSON attuale (se esiste)
      - name: Backup Current JSON
        run: cp directories.json directories.json.bak || echo "No previous JSON to backup"

      # Debug della directory notes
      - name: List Notes Directory
        run: |
          echo "Contents of notes directory:"
          ls -R notes || echo "Notes directory not found"

      # Esecuzione dello script per generare il nuovo JSON
      - name: Run JSON Generator Script
        run: |
          chmod +x create_json.sh
          ./create_json.sh
          echo "Generated JSON content:"
          cat directories.json

      # Confronto tra vecchio e nuovo JSON
      - name: Compare JSON Files
        run: |
          if diff directories.json directories.json.bak; then
            echo "No changes in directories.json"
            exit 0
          else
            echo "directories.json has changed:"
            diff directories.json directories.json.bak
          fi

      # Debug Git per verificare modifiche
      - name: Debug Git
        run: |
          git status
          git diff directories.json

      # Commit e push delle modifiche
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add directories.json
          git commit -m "Update directories.json [CI]" || echo "No changes to commit"
          git push origin main || echo "Push failed"
