name: Update directories.json

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Backup Current JSON
        run: cp assets/data/directories.json assets/data/directories.json.bak || echo "No previous JSON to backup"

      - name: List Notes Directory
        run: |
          echo "Contents of notes directory:"
          ls -R notes || echo "Notes directory not found"

      - name: Run JSON Generator Script
        run: |
          chmod +x scripts/create_json.sh
          ./scripts/create_json.sh
          echo "Generated JSON content:"
          cat assets/data/directories.json

      - name: Compare JSON Files
        run: |
          if diff assets/data/directories.json assets/data/directories.json.bak; then
            echo "No changes in directories.json"
          else
            echo "directories.json has changed:"
            diff assets/data/directories.json assets/data/directories.json.bak || true
          fi

      - name: Debug Git
        run: |
          git status
          git diff assets/data/directories.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add assets/data/directories.json
          git commit -m "Update directories.json [CI]" || echo "No changes to commit"
          git push origin main || echo "Push failed"
