name: Generate Directories JSON

on:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if script exists
        run: ls -la script.sh

      # execute .sh
      - name: Run JSON Generator Script
        run: |
          chmod +x create_json.sh
          ./create_json.sh
