name: Execute SH Script

on:
  push:
    branches:
      - main

jobs:
  run-sh:
    runs-on: ubuntu-latest

    steps:
      # Esegui il checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Verifica i file presenti nella workspace
      - name: List files in workspace
        run: ls -R

      # Esegui lo script per generare il JSON
      - name: Run JSON Generator Script
        run: |
          chmod +x create_json.sh
          ./create_json.sh
