name: Update directories.json

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove cached JSON
        run: rm -f directories.json

      - name: Run JSON Generator Script
        run: |
          chmod +x create_json.sh
          ./create_json.sh
          echo "Generated JSON content:"
          cat directories.json

      - name: Debug Git
        run: |
          git status
          git diff directories.json

      - name: Force Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add directories.json --force
          git commit -m "Update directories.json [CI]" || echo "No changes to commit"
          git push origin main || echo "Push failed"
